
# use an additional file to keep track of who has been emailed
# so they won't be emailed again
# file does not need to exist on first run; will be generated if true
# history.json
use_email_file: true

# how far back to query
post_age: now-30d

# how many results to get
num_results: 100

# file that has your gmail password
password: password.txt

# query is for the actual search sent to the server,
# separated by OR
#
# keywords are used to search the post description that returns
# to determine relevancy
categories:
  ios:
    query:
      - ios
    keywords:
      - ios
      - swift
      - objective-c
      - objective c
    email_primary: \nI have a good deal of iOS and Swift experience, with an app on the app store and a few more in the pipeline.
    email_secondary: iOS and Swift (with an app in the app store)
  java:
    query:
      - java
    keywords:
      - java
    email_primary: \nI have a good deal of experience with Java as its my first language and the language of instruction at my alma mater.
    email_secondary: Java
  web:
    query:
      - angular
      - angularjs
      - angular2
      - angular.js
    keywords:
      - angular
      - angularjs
      - angular js
      - html
      - css
      - javascript
    email_primary: \nI have web development experience (specifically with Angular), both in creating my own sites and with Ionic.
    email_secondary: web development (specifically angular2)
  aws:
    query:
      - aws
    keywords:
      - aws
      - amazon
      - cloud
    email_primary: \nI have a fair bit of experience with cloud solutions; I was most recently at Cardinal Health working with AWS on their cloud engineering team.
    email_secondary: AWS
  junior:
    query:
      - junior
    keywords:
      - junior
      - entry

      # if there's no email_primary for a category and it is the highest ranked,
      # neither email_primary nor email_secondary will be inserted into the email

email:

  from: kochrt@gmail.com
  company_alternative: applying

  # { site }              Posting site (Hacker News, Stack Overflow, etc.)
  # { company }           Company name else company_alternative
  # { email_primary }     Primary match email blurb from the categories dictionary above
  # { email_secondary }   Extra email part w/preamble (excluded if no {2})
  # { link }              Link

  subject: Interested in { company }

  # Do this because the secondary email blurb is not included if the
  # primary isn't either, or if there is only one match and therefore no secondary
  email_secondary_preamble: I also have experience with
  email_secondary_suffix: .\n
  email_secondary_alternative: \n

  body: |
    Hello,

    I saw your post on { site } and thought I would send over my information. My name is Rob Koch, I'm a senior computer science major at Miami University. I'll be graduating in May and am looking for full-time opportunities.
    { email_primary } { email_secondary }
    <a href="robko.ch">Here's my resume</a> - if you think there might be something for me I'd love to hear back from you.

    Thanks!

    Rob Koch