
# query is for the actual search sent to the server,
# separated by OR
# keywords are used to search the post description that returns
# to determine relevancy
categories:
  ios:
    query:
      - 'ios'
    keywords:
      - 'ios'
      - 'swift'
      - 'objective-c'
      - 'objective c'
    email: >
      I have a good deal of iOS and Swift experience,
      with an app on the app store and a few more in the pipeline.
  java:
    query:
      - 'java'
    keywords:
      - 'java'
    email: >

  web:
    query:
      - 'angular'
      - 'angularjs'
      - 'angular2'
      - 'angular.js'
    keywords:
      - 'angular'
      - 'angularjs'
      - 'angular js'
      - 'html'
      - 'css'
      - 'javascript'
    email: >
      I have web development experience (specifically with Angular),

  aws:
    query:
      - 'aws'
    keywords:
      - 'aws'
      - 'amazon'
      - 'cloud'
  junior:
    query:
      - 'junior'
    keywords:
      - 'junior'
      - 'entry'

email:
  smtp_server: 'something.google.com'

  # {0} - Posting site (Hacker News, Stack Overflow, etc.)
  # {1} - Company name
  # {2} - Primary match email blurb

  subject: 'Interested in {1}'

  body_prefix: |
    Hello,

    I saw your post on {0} and thought I would send over my information. My name is Rob Koch, I'm a senior computer science major at Miami University. I'll be graduating in May and am looking for full-time opportunities.

    {2}

    <a href='robko.ch'>Here's my resume</a> - if you think there might be something for me I'd love to hear back from you.

    Thanks!

    Rob Koch
